# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ffda50f20af2d9b53e54bbbd6344632ed02c0d7b756f45baf98778927aef683502e862c4e892279f23151b2f705da91662136baf647bce97f6be994f432771d

test:
  secret_key_base: 22bc517dc8d044c0c07a2eaa348a6c76a5c35f797ba70d1c287f7850a6fa3a59ab1e342062ade4725e4af0cb7de8057ccdfa211e16fcd69bbc196efaf7d1c3bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
